---
title: 小ネタ
author: paithiov909
date: '2020-07-11'
lastmod: "`r Sys.Date()`"
slug: genshijin
categories: []
tags:
  - NLP
description: '小ネタです'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = "styler",
  collapse = TRUE,
  comment = "#>"
)

stopifnot(require(tidyverse))
stopifnot(require(tangela))
```

## ゲンシジン ナル

助詞を除いてカタコトの日本語にするやつ

```{r func}
genshijin <- function(text) {
  `%without%` <- purrr::negate(`%in%`)
  df <- tangela::kuromoji(text) %>%
    purrr::map_dfr(~ data.frame(
      feature = purrr::pluck(., "feature"),
      stringsAsFactors = FALSE
    )) %>%
    tidyr::separate(
      col = "feature",
      into = c(
        "品詞",
        "品詞細分類1",
        "品詞細分類2",
        "品詞細分類3",
        "活用形",
        "活用型",
        "原形",
        "読み",
        "発音"
      ),
      sep = ",",
      fill = "right"
    )
  res <- df %>%
    tidyr::drop_na() %>%
    dplyr::filter(!!sym("品詞細分類1") %without% c(
      "格助詞",
      "係助詞",
      "終助詞",
      "副詞化",
      "特殊"
    )) %>%
    dplyr::pull("読み") %>%
    paste(collapse = " ")
  return(res)
}
```

```{r}
genshijin("メガネは顔の一部じゃない あなたはわたしの全てじゃない")
```

## 名詞をランダムに「ヒャッハァー！」に置換

```{r hyahhaaa}
hyahhaaa <- function(text, replacement = "ヒャッハァーー！", pos = "名詞", p = 0.8) {
  df <- tangela::kuromoji(text) %>%
    purrr::map_dfr(~ data.frame(
      surface = purrr::pluck(., "surface"),
      feature = purrr::pluck(., "feature"),
      stringsAsFactors = FALSE
    )) %>%
    tidyr::separate(
      col = "feature",
      into = c(
        "品詞",
        "品詞細分類1",
        "品詞細分類2",
        "品詞細分類3",
        "活用形",
        "活用型",
        "原形",
        "読み",
        "発音"
      ),
      sep = ",",
      fill = "right"
    )
  res <- df %>%
    dplyr::rowwise() %>%
    dplyr::mutate(str = dplyr::if_else(
      !!sym("品詞") %in% c(pos) & runif(1) <= p,
      replacement,
      !!sym("surface")
    )) %>%
    dplyr::pull("str") %>%
    paste(collapse = "")
  return(res)
}
```

```{r}
hyahhaaa("恋するだけが乙女じゃない 素直なだけがいい子じゃない")
```

## 参考

### ゲンシジン ナル

- [【R言語】Rでゲンシジンになってみた - Qiita](https://qiita.com/taro_9674/items/e02119ab26376979a489)
- [オレ プログラム ウゴカス オマエ ゲンシジン ナル - Qiita](https://qiita.com/Harusugi/items/f499e8707b36d0f570c4)
- [Mecabなど形態素解析で使うIPA品詞体系（品詞ID｜pos-id） - MS Tech](http://miner.hatenablog.com/entry/323)

### 名詞をランダムに「ヒャッハァー！」に置換

- [日本語文の名詞をランダムに「ヒャッハァー！」に置換するＲスクリプト - こにしき（言葉・日本社会・教育）](https://terasawat.hatenablog.jp/entry/20100711/1278861735)
