---
title: Rで言語処理100本ノックを解くわけがない（２）
author: paithiov909
date: "`r Sys.Date()`"
lastmod: '2020-07-11'
slug: 100-knocks-2020-2
categories: []
tags:
  - NLP
description: 'Rで言語処理100本ノック 2020（２）'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = "styler",
  collapse = TRUE,
  comment = "#>"
)
stopifnot(require(tidyverse))
```

## 形態素解析

気をきかせて{readtext}で読みこんでおきます。

```{r}
temp <- tempfile(fileext = ".txt")
download.file("https://nlp100.github.io/data/neko.txt", temp)
neko <- readtext::readtext(temp, encoding = "UTF-8")
neko$text[1] %>%
    readr::read_lines(skip_empty_rows = TRUE) %>%
    length()
```

### 30. 形態素解析結果の読み込み

{RMeCab}はtaggerをラップしていて必要な情報を取りづらいので、[オレオレパッケージ](https://paithiov909.github.io/rjavacmecab/)を使います。動くはずです（ただし、{RMeCab}などに比べて5~10倍程度は遅い）。{RcppMeCab}でもできますが、公式のリポジトリのソースはWindows環境だとビルドにコケるのでUNIX系の環境が必要です（2020年5月現在）。

データフレームで持ちたいのですが、すべて変換すると死ぬほど時間がかかるのでここでは一部の解析結果だけ使います。

```{r}
neko_txt_mecab <- rjavacmecab::cmecab(neko$text[1])[1:900] %>%
    purrr::map_dfr(function(line){
        row <- stringr::str_split(line, " ", simplify = TRUE)
        attr <- rjavacmecab::tokenize(row[1, 2]) %>%
            t() %>%
            as.data.frame(stringsAsFactors = FALSE)
        res <- row[1, 1] %>%
            as.data.frame(stringsAsFactors = FALSE) %>%
            dplyr::bind_cols(attr)
        return(res)
    })
colnames(neko_txt_mecab) <- c(
    "Surface",
    "POS1",
    "POS2",
    "POS3",
    "POS4",
    "X5StageUse1",
    "X5StageUse2",
    "Base",
    "Reading",
    "Pronunciation"
)
head(neko_txt_mecab)
```

### 31. 動詞

```{r}
neko_txt_mecab %>%
    dplyr::filter(POS1 == "動詞") %>%
    dplyr::select(Surface) %>%
    head()
```

### 32. 動詞の原形

```{r}
neko_txt_mecab %>%
    dplyr::filter(POS1 == "動詞") %>%
    dplyr::select(Base) %>%
    head()
```

### 33. 「AのB」

```{r}
neko_txt_mecab %>%
    tibble::rowid_to_column() %>%
    dplyr::filter(Surface == "の") %>%
    dplyr::pull(rowid) %>%
    purrr::keep(~ neko_txt_mecab$POS1[. - 1] == "名詞" && neko_txt_mecab$POS1[. + 1] == "名詞") %>%
    purrr::map_chr(~ stringr::str_c(
        neko_txt_mecab$Surface[. - 1],
        neko_txt_mecab$Surface[.],
        neko_txt_mecab$Surface[. + 1],
        collapse = ""
    ))
```

### 34. 名詞の連接

（これよくわからない）

```{r}
idx <- neko_txt_mecab %>%
    tibble::rowid_to_column() %>%
    dplyr::filter(POS1 == "名詞") %>%
    dplyr::pull(rowid) %>%
    purrr::discard(~ neko_txt_mecab$POS1[. + 1] != "名詞")

search_in <- idx

purrr::map_chr(search_in, function(idx) {
    itr <- idx
    res <- stringr::str_c(neko_txt_mecab$Surface[idx])
    while (neko_txt_mecab$POS1[itr + 1] == "名詞") {
        res <- stringr::str_c(res, neko_txt_mecab$Surface[itr + 1])
        search_in <<- purrr::discard(search_in, ~ . == itr + 1)
        itr <- itr + 1
    }
    return(res)
})
```

### 35. 単語の出現頻度

```{r}
neko_txt_mecab %>%
    dplyr::group_by(Base) %>%
    dplyr::count(Base, sort = TRUE) %>%
    head()
```

### 36. 頻度上位10語

```{r}
neko_txt_mecab %>%
    dplyr::group_by(Base) %>%
    dplyr::count(Base, sort = TRUE) %>%
    head(10) %>%
    ggplot(aes(x = reorder(Base, -n), y = n)) +
        geom_col() +
        labs(x = "Surface form") +
        theme_light()
```

### 37. 「猫」と共起頻度の高い上位10語

解釈のしかたが複数あるけれど、はじめに形態素解析する段階で文区切りを無視してしまったので、ここではbi-gramを数えてお茶をにごします。

```{r}
neko_txt_mecab %>%
    tibble::rowid_to_column() %>%
    dplyr::filter(Surface == "猫") %>%
    dplyr::mutate(Colocation = stringr::str_c(Surface, neko_txt_mecab$Surface[rowid + 1], sep = " - ")) %>%
    dplyr::group_by(Colocation) %>%
    dplyr::count(Colocation, sort = TRUE) %>%
    head(10) %>%
    ggplot(aes(x = reorder(Colocation, -n), y = n)) +
        geom_col() +
        labs(x = "Colocation", y = "Freq") +
        theme_light()
```

### 38. ヒストグラム

```{r}
neko_txt_mecab %>%
    dplyr::group_by(Base) %>%
    dplyr::count(Base) %>%
    ggplot(aes(x = reorder(Base, - n), y = n)) +
        geom_col() +
        labs(x = "", y = "Freq") + 
        theme_light()
```

### 39. Zipfの法則

~~ずっと雰囲気で書いている ggplot2なんもわからん~~

```{r}
count <- neko_txt_mecab %>%
    dplyr::group_by(Base) %>%
    dplyr::count(Base) %>%
    dplyr::ungroup()
count %>%
  tibble::rowid_to_column() %>%
  dplyr::mutate(rank = nrow(count) + 1 - dplyr::min_rank(count$n)[rowid]) %>%
  ggplot(aes(x = rank, y = n)) +
        geom_point() +
        labs(x = "Rank of Freq", y = "Freq") +
        scale_x_log10() +
        scale_y_log10() +
        theme_light()
```

## セッション情報

```{r}
devtools::session_info()
```
